### PR TITLE
Update README.txt

### PR DESCRIPTION
**Pull request by barej**

### CODE REVIEW

**Comment by makulik** [comment]
That's not subject of a technical readme, sorry.
Request declined.

**Comment by barej** [comment]
Then, how come your behaviour on stackoverflow is technical?

**Comment by makulik** [comment]
Hi,

	What do you actually mean? Why are you stalking me this way? 

	Do you actually think I'm a nazi because I'm german? 

	My SO user profile (which I assume is a right place to make an
anti-racist statement), should well show I'm not, but just the
opposite and fought them whenever met on the internet or in real life.


	Do you think my behavior on SO is actually contradictory vs. what
I've been stating in my profile? 

	However, as I've mentioned about your pull request, the REAME.txt of
a techincal project isn't the right place for such statement, and
therefore I declined. 

	Best regards, 

	Günther 

	P.S.: You can well talk peer to peer with me on this com channel, or
the other mail address I left in my profile. 

	-----Original-Nachricht----- 

	Betreff: Re: [sttcl] Update README.txt (#2) 

	Datum: Tue, 03 Feb 2015 08:20:12 +0100 

	Von: "Barej (Anti-Racism)" <notifications@github.com> 

	An: makulik/sttcl <sttcl@noreply.github.com> 

	Then, how come your behaviour on stackoverflow is technical? 

	—
Reply to this email directly or view it on GitHub [1].

Links:
------
[1] https://github.com/makulik/sttcl/pull/2#issuecomment-72605611

**Comment by barej** [comment]
I feel easy to talk here. So why do you mark questions of only us as duplicate and give us serial downvote?

**Comment by makulik** [comment]
You're obviously paranoic, I never did so targeting you personally or
because of any racist judgements.

	Best regards, 

	Günther 

	-----Original-Nachricht----- 

	Betreff: Re: [sttcl] Update README.txt (#2) 

	Datum: Sun, 08 Feb 2015 14:26:38 +0100 

	Von: "Barej (Anti-Racism)" <notifications@github.com> 

	An: makulik/sttcl <sttcl@noreply.github.com> 

	I feel easy to talk here. So why do you mark questions of only us as
duplicate and give us serial downvote? 

	—
Reply to this email directly or view it on GitHub [1].

Links:
------
[1] https://github.com/makulik/sttcl/pull/2#issuecomment-73410716

**Comment by barej** [comment]
Your disgusting behaviour is always bothering to everybody.  You are ill for bothering others to prove your power. You can never defeat us by a few downvotes.

**Pull request closed without merging**
